version: '3'

services:
  development:
    build: .
    ports:
      - "8080:80"
    volumes:
      - development_images:/usr/share/nginx/html/images

  production:
    build: .
    ports:
      - "8081:80"
    volumes:
      - production_images:/usr/share/nginx/html/images

  test:
    build: .
    ports:
      - "8082:80"
    volumes:
      - test_images:/usr/share/nginx/html/images

volumes:
  development_images:
  production_images:
  test_images:
