name: Transfer Build Files

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: wsl-test-runner


    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build and run Docker containers locally
        run: |
          cd /home/ubuntu/Project_Compose
          docker-compose -f compose_file.yaml up -d
